### ISSUE TITLE
Populate not working

### ISSUE THREAD

**Issue by petetnt** [gian788/docooment#7]
I have a correctly working Mongoose setup with that uses [http://mongoosejs.com/docs/populate.html](population) to populate an array of `ObjectID's`. 

However, when switching to Docooment-setup on our Azure cloud the process throws the following error:

``` bash
Tue Jul 14 2015 12:31:33 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Object #<Object> has no method 'populate'
    at Function.Model.populate (D:\home\site\wwwroot\node_modules\docooment\lib\model.js:2053:21)
    at EventEmitter.<anonymous> (D:\home\site\wwwroot\backend\routes.js:55:29)
    at EventEmitter.<anonymous> (D:\home\site\wwwroot\node_modules\docooment\node_modules\mpromise\lib\promise.js:180:45)
    at EventEmitter.emit (events.js:95:17)
    at Promise.safeEmit (D:\home\site\wwwroot\node_modules\docooment\node_modules\mpromise\lib\promise.js:83:21)
    at Promise.fulfill (D:\home\site\wwwroot\node_modules\docooment\node_modules\mpromise\lib\promise.js:104:24)
    at D:\home\site\wwwroot\node_modules\docooment\lib\query.js:1056:26
    at model.Document.init (D:\home\site\wwwroot\node_modules\docooment\lib\document.js:249:11)
    at completeMany (D:\home\site\wwwroot\node_modules\docooment\lib\query.js:1054:12)
    at Object.cb (D:\home\site\wwwroot\node_modules\docooment\lib\query.js:1020:11)
    at Object._onImmediate (D:\home\site\wwwroot\node_modules\docooment\node_modules\mquery\lib\utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
Application has thrown an uncaught exception and is terminated:
```

**Comment by petetnt** [comment]
I made some effort to get to the bottom of this, basically the line that fails isn't `Model#populate` like I expected but `lib/utils` not having the `populate` function

``` js
  var paths = utils.populate(paths);
```

Relevant `mongoose/lib/utils#populate` looks like [this](https://github.com/Automattic/mongoose/blob/master/lib/utils.js#L483) 

edit: followed the chain down the rabbithole, no errors but populate promises don't resolve either.
